[tool.poetry]
name = "mspaint"
version = "0.1.0"
description = "multi-engine painting of mass spec data"
authors = ["Shaurya Chanana", "John T. Prince"]
readme = "README.md"
license = "GNU General Public License v2.0"
packages = [{include = "mspaint"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
numpy = "^2"
holoviews = "^1"
plotly = "^5"
bokeh = "^3"
matplotlib = "^3"
pyparsing = "^3.0.9"
pyarrow ="^16"
kaleido = "0.2.1" # for plotly svg saves
selenium = "^4.9.1" # for bokeh png saves
nbformat = "^5.10.4"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3"
ruff = "^0"
ipykernel = "^6"

[tool.poetry.group.test.dependencies]
pytest = "^7"
snapshottest = "^0.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    "tests/**/snapshots",
    "notebooks",
    "example_data/"
]
