[project]
name = "mspaint"
version = "0.2.0"
description = "multi-engine painting of mass spec data"
authors = [
    { name = "Shaurya Chanana" },
    { name = "John T. Prince" },
]
requires-python = ">=3.10,<3.12"
readme = "README.md"
license = "GPL-2.0"
dependencies = [
    "numpy>=2,<3",
    "holoviews>=1,<2",
    "plotly>=5,<6",
    "bokeh>=3,<4",
    "matplotlib>=3,<4",
    "pyparsing>=3.0.9,<4",
    "pyarrow>=16,<17",
    "kaleido==0.2.1",
    "selenium>=4.9.1,<5",
    "nbformat>=5.10.4,<6",
]

[dependency-groups]
dev = [
    "pre-commit>=3,<4",
    "ruff>=0,<1",
    "ipykernel>=6,<7",
    "pytest>=7,<8",
    "snapshottest>=0.6.0,<0.7",
]

[tool.uv]
default-groups = ["dev", ]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[tool.hatch.build.targets.sdist]
include = ["mspaint"]

[tool.hatch.build.targets.wheel]
include = ["mspaint"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    "tests/**/snapshots",
    "notebooks",
    "example_data/"
]
