name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Load pre-commit-cache
        id: pre-commit-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ matrix.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Load uv-venv-cache
        id: cached-uv-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/uv.lock') }}

      - name: Install dependencies
        run: |
          uv sync --all-groups --no-install-project
        if: steps.cached-uv-venv.outputs.cache-hit != 'true'

      - name: Check with pre-commit
        run: |
          uv run pre-commit install
          uv run pre-commit run --all-files
      - name: Test with pytest
        run: |
          uv run pytest -m 'not e2e' -v
